services:
  - type: web
    name: rental-properties-app
    env: node
    buildCommand: |
      cd client && npm install && npm run build && cd .. && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000